name: Get Food Schedule 🍔
on:
  workflow_dispatch:
  schedule:
  - cron: "0 1 * * 1-5"
env: # Or as an environment variable
    CLIENT_ID: ${{ secrets.SKOLMATEN_CLIENT_ID }}
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://www.skolmaten.se/api/3/menu/?school=6527553372160000
          configuration: '{ "method": "GET", "headers": {"client": "${{ secrets.SKOLMATEN_CLIENT_ID }}" }'
          save-location: food-schedule/data.json
